version: "3.8"

services:
  db:
    image: postgres:15.3-alpine
    container_name: "database"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - fullstack
  app:
    build: .
    container_name: "rest-api"
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db # Use the service name "db" as the host
    depends_on:
      - db
    networks:
      - fullstack
    command: >
      /bin/sh -c "
        while ! nc -z -w1 db 5432;
        do
          echo waiting for db;
          sleep 1;
        done;
        echo db is ready!;
        ./main
        "

volumes:
  postgres-db:

networks:
  fullstack:
    driver: bridge
